# -*- coding: utf-8 -*-
from datetime import date
B, I, F = "Instagram + Facebook", "Instagram", "Facebook"
RH, NA, FE, FA, WH, CS = ("Rhythm of the Day","Nature & Season","Festivals & Gatherings",
                          "Faces of Cedar Grove","Why We Do This","Come and See")

# date, channel, pillar, post idea, caption starter, asset needed, ties to
P = [
# ---------------- SEPTEMBER ----------------
("2026-09-08",B,RH,"First day of school","Today the trail filled up again. Our first morning of the 2026–27 year began the way every morning does — with the walk down to the school.","Children walking the winding trail, from behind","First day of school"),
("2026-09-10",B,WH,"Why we walk down the trail","There is a reason we ask families to park at the top and walk down. The trail is not an inconvenience; it is the first lesson of the day.","The winding trail, morning light","—"),
("2026-09-11",I,FA,"Meet the people who greet your children","A short introduction to the faces your children will see each morning this year.","Carousel: one portrait per teacher","—"),
("2026-09-15",B,NA,"Two hours outside, minimum","Even on the coldest months, the children are outdoors at least two hours a day. In September, it is most of it.","Wide shot, children scattered across the wooded playground","—"),
("2026-09-17",B,RH,"Morning Gratitude","We begin as a whole school — song, movement, and a moment of gratitude — before anyone opens a book.","Morning circle, whole school","—"),
("2026-09-22",B,NA,"First day of autumn","The maples along the trail turned this week. The children noticed before we did.","Close-up of turning leaves in a child's hand","Autumn equinox"),
("2026-09-24",I,RH,"The work of the hands","Beeswax warms in small palms until it is soft enough to become something.","Hands modelling beeswax, close-up","—"),
("2026-09-25",B,FE,"Festival of Courage — next week","Our first festival of the year asks something of the children: to try the thing that feels a little too big.","Last year's Festival of Courage","Festival of Courage, Sep 29"),
("2026-09-29",B,FE,"Festival of Courage","Today the children did brave things. Small ones, mostly. That is how courage starts.","Candid moments from the festival","Festival of Courage"),
("2026-09-30",B,WH,"National Day for Truth and Reconciliation","HOLD FOR REVIEW — this post should be written or approved by Kerri (Kaya'tahente) Smart, a Bear Clan woman from Tyendinaga Mohawk Territory. Do not post generic copy.","To be decided with Kerri","Truth and Reconciliation Day"),
("2026-10-02",I,FE,"Festival of Courage — in pictures","A few moments from Tuesday.","Carousel, 6–8 photos","Festival of Courage"),
# ---------------- OCTOBER ----------------
("2026-10-06",B,FE,"Harvest Festival — Friday, families welcome","Our first family gathering of the year. Friday 3:30–5pm, on the farm. Bring a jar for the apple pressing.","Last year's harvest table","Harvest Festival, Oct 9"),
("2026-10-08",I,RH,"Baking day","The whole school smells like bread on Thursdays. The children knead it themselves.","Dough on the board, flour on hands","—"),
("2026-10-09",B,FE,"Harvest Festival today","3:30 this afternoon. We will see you down the trail.","Story-friendly graphic + reminder","Harvest Festival"),
("2026-10-13",B,FE,"Thank you for a full table","What our families brought on Friday, and what the children made of it.","Carousel from the festival","Harvest Festival recap"),
("2026-10-15",B,WH,"Why our classes are mixed-age","A six-year-old learning beside an eight-year-old is not a compromise. It is the point.","Two children of different ages working together","—"),
("2026-10-20",B,WH,"Mud season starts now","A short, practical guide to what actually keeps a child warm and dry here. Mittens beat gloves. Wool beats cotton.","Flat-lay of boots, mittens, wool socks","Handbook — Gear & Clothing"),
("2026-10-22",B,FA,"Meet Henry Lear","Our Lead Grade School Teacher on why he came to Cedar Grove.","Henry's portrait + a classroom candid","—"),
("2026-10-23",B,CS,"Come and walk the land","The best way to know if Cedar Grove is right for your child is to visit. Tours are running through the autumn.","Trail or school building, inviting wide shot","Admissions"),
("2026-10-26",I,RH,"No school today","PA Day — teachers are meeting families for conferences.","Simple text-on-cream graphic","PA Day / Conferences"),
("2026-10-28",B,NA,"The land in late October","Seven hundred acres of farm and forest, and the children know the good parts.","Landscape, autumn colour","—"),
("2026-10-30",I,FE,"Lanterns are coming","Next week the children begin making them. Quietly, over several days.","Lantern-making materials","Lantern Festival build-up"),
# ---------------- NOVEMBER ----------------
("2026-11-03",B,FE,"Making the lanterns","Tissue, glue, patience. The making matters as much as the walking.","Children making lanterns","Lantern Festival build-up"),
("2026-11-05",I,FE,"Tomorrow we walk with light","A quiet festival for the darkening year.","Single lit lantern","Lantern Festival"),
("2026-11-06",B,FE,"Lantern Festival","Tonight the children carried their own light down the trail.","Lantern walk at dusk","Lantern Festival"),
("2026-11-10",B,FE,"Lantern Festival — in pictures","Photographs from Friday evening.","Carousel","Lantern Festival recap"),
("2026-11-11",B,WH,"Remembrance Day","We keep this simply and age-appropriately, as we do each year.","Restrained, simple graphic","Remembrance Day"),
("2026-11-17",B,WH,"Media is for home, not school","We do not judge how families handle screens. But inside these walls we protect something specific: a child's own imagination.","Children in unstructured play","Handbook — Electronics & Media"),
("2026-11-19",I,RH,"Main lesson books","Every child makes their own textbook. Written, drawn, and bound by hand.","Open main lesson book pages","—"),
("2026-11-24",B,NA,"There is no bad weather","November is when families discover their child is tougher than they thought.","Children outside in grey weather, absorbed","—"),
("2026-11-26",B,FA,"A parent's words","'From the moment you arrive at Cedar Grove, you immediately feel a sense of calmness and connection.' — Melissa Machnik","Quote card in brand colours","Testimonial"),
("2026-11-27",B,CS,"Thinking about next September?","Tours are running through the winter. Come see an ordinary day — that is the most honest thing we can show you.","Warm interior or trail shot","Admissions"),
# ---------------- DECEMBER ----------------
("2026-12-01",B,NA,"The quiet season","The year turns inward. So does the classroom.","Candlelight, low winter sun","—"),
("2026-12-03",I,RH,"Handwork","Small hands, wool, and a great deal of concentration.","Knitting or finger-knitting close-up","—"),
("2026-12-08",B,FE,"What is a Spiral Walk?","For families new to Cedar Grove: an explanation of the quietest and most beautiful of our festivals.","Last year's spiral of greenery","Spiral Walk build-up"),
("2026-12-10",B,WH,"Winter gear that actually works","Wool base layers, mittens over gloves, and an extra pair of everything at school.","Gear flat-lay, winter version","Handbook — Gear & Clothing"),
("2026-12-15",B,FE,"Spiral Walk — Friday, families welcome","Friday 3:30–5pm. Dress warmly; we will be outside in the dark.","Spiral of evergreen boughs","Spiral Walk, Dec 18"),
("2026-12-17",I,FE,"Tomorrow evening","One candle, one child at a time.","Single candle in the spiral","Spiral Walk"),
("2026-12-18",B,FE,"Spiral Walk","Each child walked the spiral alone and came back carrying light. Thank you for standing in the cold with us.","Spiral walk photographs","Spiral Walk"),
("2026-12-22",B,FA,"Wishing you a restful winter","School resumes January 5th. Until then — rest, and time outside.","Winter landscape on the farm","Winter holidays"),
("2026-12-30",I,FA,"Our year, so far","A look back at the first half of the school year.","Carousel: best photos Sept–Dec","Year in review"),
# ---------------- JANUARY ----------------
("2027-01-05",B,RH,"Back down the trail","First morning of the new year. Snow on the path and a great deal to talk about.","Children returning, winter","First day back"),
("2027-01-07",B,NA,"Winter forest","The woods are a different place in January. Quieter, and easier to read.","Bare trees, tracks in snow","—"),
("2027-01-12",B,CS,"Applications open for September 2027","Enrolment for the 2027–28 year is now open, JK through Grade 5. Places are limited by design — our ratio is 8:1.","Bright, welcoming school photo","ADMISSIONS OPENS"),
("2027-01-14",B,RH,"What a day actually looks like","8:40 arrival and Morning Gratitude. Main lesson. Outdoors. An unhurried lunch. Arts and handwork. Home at 3:30.","Carousel following one day, morning to afternoon","Admissions support"),
("2027-01-15",B,CS,"Book a tour","We would rather show you a Tuesday than a brochure.","Trail invitation shot","Admissions"),
("2027-01-19",B,CS,"Inside the Kindergarten and Grade One room","Play-based, unhurried, and busier than it looks.","Kindergarten room and materials","Admissions — Early Years"),
("2027-01-21",B,FA,"Meet Kerri (Kaya'tahente) Smart","Our Lead Kindergarten Teacher, and a certified Forest and Nature School practitioner.","Kerri's portrait + classroom candid","—"),
("2027-01-26",B,CS,"Inside the Grade School","Main lesson blocks, three to four weeks at a time, built around story and image.","Grade school children at work","Admissions — Lower Grades"),
("2027-01-28",B,FA,"A parent's words","'He looks forward to attending school everyday and always comes home feeling fulfilled.' — Sarah Fournier","Quote card","Testimonial"),
("2027-01-29",I,RH,"No school today","PA Day.","Text-on-cream graphic","PA Day"),
# ---------------- FEBRUARY ----------------
("2027-02-02",B,FE,"Mid-Winter Festival — Friday","The turning point of the cold season. An internal celebration, just for the children.","Last year's mid-winter imagery","Mid-Winter Festival build-up"),
("2027-02-04",I,NA,"Light returning","Noticeably longer afternoons. The children are the first to say so.","Late afternoon light through trees","—"),
("2027-02-05",B,FE,"Mid-Winter Festival","Songs, warmth, and something sweet in the middle of the coldest month.","Festival photographs","Mid-Winter Festival"),
("2027-02-09",I,FE,"Mid-Winter — in pictures","A few moments from Friday.","Carousel","Mid-Winter recap"),
("2027-02-11",B,CS,"Eight children to one teacher","What an 8:1 ratio means in practice: your child is known, not managed.","Teacher with a small group","Admissions"),
("2027-02-16",B,FA,"Family Day","No school yesterday. We hope you were outside.","Family-in-nature image","Family Day"),
("2027-02-18",B,CS,"Part-time is for every family","Not only for homeschoolers. Kinder and Grade One families choose 1–4 days; Grade 2–5 students join us on Fridays.","Part-time programme photo","Admissions — Part-Time"),
("2027-02-23",B,NA,"Reading the winter trees","The older children are learning to identify natives by bark and bud alone.","Child examining bark","Native tree programme"),
("2027-02-25",B,CS,"Open house — come and see","An invitation to walk the land, meet the teachers, and ask anything.","Wide, welcoming shot","Admissions"),
("2027-02-26",B,FA,"A parent's words","'Teachers know your children by name and guide rather than manage a crowd.' — Leslie Ng","Quote card","Testimonial"),
# ---------------- MARCH ----------------
("2027-03-02",B,CS,"A note on timing","Places for September fill through the spring. If you are considering Cedar Grove, now is the moment to visit.","School building, spring light","Admissions deadline push"),
("2027-03-04",B,NA,"Sap is running","The maples are giving. The children are tasting.","Sap bucket or boiling","—"),
("2027-03-05",I,RH,"Spring break begins Monday","Two weeks off. See you March 22nd.","Simple graphic","Spring Break"),
("2027-03-10",I,NA,"Nature does not take a break","A few gentle ideas for outdoor time over the holiday.","Seasonal outdoor image","Spring Break"),
("2027-03-17",I,RH,"See you Monday","School resumes March 22nd.","Trail image","Spring Break ends"),
("2027-03-23",B,RH,"Back at it","Spring smells different. The children ran the last stretch of the trail.","Children returning, spring mud","—"),
("2027-03-25",B,FE,"Seed Festival — next Friday","Families welcome, 3:30–5pm. We will be planting, and sending seedlings home.","Seed trays, soil","Seed Festival build-up"),
("2027-03-30",B,NA,"The native tree programme","The older children collected seeds from the farm in the autumn. This week they became seedlings.","Children with seed trays","Native tree programme"),
("2027-04-01",I,FE,"Tomorrow — Seed Festival","3:30 on the farm. Bring something to carry a seedling home in.","Reminder graphic","Seed Festival"),
# ---------------- APRIL ----------------
("2027-04-02",B,FE,"Seed Festival","Everything we planted today is going home with somebody.","Festival photographs","Seed Festival"),
("2027-04-06",I,FE,"Seed Festival — in pictures","A few moments from Friday.","Carousel","Seed Festival recap"),
("2027-04-08",B,WH,"April mud is a curriculum","On the wettest days the children learn the most about their own capability.","Muddy boots, delighted faces","Handbook — Gear"),
("2027-04-13",B,CS,"Enrolment closing for September","A few places remain for 2027–28. If you have been meaning to book a tour, this is the week.","Warm school image","Admissions deadline"),
("2027-04-15",B,FA,"Music at Cedar Grove","An introduction to Sara Benedict and the place of song in our week.","Music class candid","—"),
("2027-04-20",I,NA,"Earth Day is Thursday","For us it is not a special day. It is Tuesday.","Children in the woods","Earth Day"),
("2027-04-22",B,NA,"Earth Day","Connection to the earth is not a topic we cover. It is the room we teach in.","Landscape or land-based work","Earth Day"),
("2027-04-27",B,FE,"Mayfair is coming","Ribbons, the maypole, and weeks of practice beforehand.","Last year's Mayfair","Mayfair build-up"),
("2027-04-29",I,RH,"Arts and handwork","Painting, baking, music — the afternoons belong to the hands.","Afternoon arts work","—"),
# ---------------- MAY ----------------
("2027-05-04",B,NA,"Birdsong survey","The children are learning to identify what they hear before they see it.","Children listening outdoors","—"),
("2027-05-06",B,FE,"Practising for the maypole","The pattern takes weeks to learn. Watching them get it is the best part.","Maypole practice","Mayfair build-up"),
("2027-05-11",I,FE,"Mayfair on Friday","An internal celebration this year — the children's own day.","Ribbons detail","Mayfair"),
("2027-05-14",B,FE,"Mayfair","Ribbons and sunshine and a morning of it.","Mayfair photographs","Mayfair"),
("2027-05-18",B,FE,"Mayfair — in pictures","Photographs from Friday.","Carousel, 8–10 photos","Mayfair recap"),
("2027-05-20",B,CS,"Last places for September","Our final call for 2027–28 enrolment.","Inviting school image","Admissions final call"),
("2027-05-26",B,NA,"The garden in May","Planted by children, weeded by children, eaten by children.","Garden beds, children working","—"),
("2027-05-28",B,FA,"Meet Jasmin Wakeling","Our Assistant Teacher, and the reason your child can name six kinds of moss.","Jasmin's portrait + outdoor candid","—"),
# ---------------- JUNE ----------------
("2027-06-02",B,FE,"Strawberry Festival — June 18th","Our last gathering of the year, and the last day of school. Families welcome, 3:30–5pm.","Strawberries, last year's festival","Strawberry Festival build-up"),
("2027-06-04",B,FA,"What a year looks like","Beginning a look back at 2026–27.","Carousel: the year in ten photos","Year in review"),
("2027-06-08",I,RH,"Their year's work","Main lesson books, paintings, and handwork go home this month.","Student work laid out","End of year"),
("2027-06-10",B,FA,"Thank you","To the families who walked the trail with us this year.","Community gathering photo","End of year"),
("2027-06-15",B,FE,"Strawberry Festival — Thursday","Our final gathering. 3:30–5pm, and then summer.","Reminder graphic","Strawberry Festival"),
("2027-06-17",I,FE,"Tomorrow","Last day, and strawberries.","Strawberry close-up","Strawberry Festival"),
("2027-06-18",B,FE,"Strawberry Festival & the last day","That is the year. Thank you, all of you. See you in September.","Festival + goodbye photographs","Last day of school"),
]
